import { ISOString } from '../Utility';

/**
 * These values should not be defined in `config.json`
 * as they are automatically generated.
 *
 * If provided, they will overwrite the default ones.
 */
export interface AutoGeneratedConfig {
    /** Current commit hash. */
    commit: string;

    startedAt: ISOString;

    production: boolean;
}
