import { HexColorString, Snowflake } from 'discord.js';
import { AutoGeneratedConfig } from './AutoGeneratedConfig';
import { ReactRole } from './ReactRole';
import { StatsBot } from './StatsBot';

/**
 * Shape of exported config that will be used through the server.
 *
 * All values are required.
 */
export interface Config extends AutoGeneratedConfig {
    /** Hex colour string for embeds. */
    embedColour: HexColorString;

    /**
     * Config related to the setting up an OAuth2 application
     * so users can link their Discord and Steam accounts.
     */
    steamLinking: {
        /**
         * Port to create simple OAuth callback webserver on.
         * @example 5000
         */
        port: number;

        /**
         * MongoDB connection string.
         * @example 'mongodb+srv://...'
         */
        mongoURI: string;

        /**
         * MongoDB database name.
         * @example 'main'
         */
        mongoDbName: string;

        /**
         * Discord client ID for the OAuth application.
         * @example '10503...'
         */
        discordClientId: string;

        /**
         * Discord client secret for the OAuth application.
         * @example 'ABC123...'
         */
        discordClientSecret: string;

        /**
         * OAuth URL with `identify` and `connections` scopes.
         * @example 'https://discord.com/api/oauth2/authorize?client_id=10503&redirect_uri=http%3A%2F%2Flocalhost%3A5000&response_type=code&scope=identify%20connections'
         */
        oAuthUrl: string;
    };

    /**
     * Config related to the main bot, which responds
     * to commands and does reaction roles.
     */
    mainBot: {
        /**
         * Discord Bot token for the main bot.
         * @example 'ABC123.DEF456...'
         */
        discordBotToken: string;

        reactRoles: {
            guildId: Snowflake;

            channelId: Snowflake;

            roles: Record<Snowflake, ReactRole>;
        };

        stats: {
            /**
             * MongoDB connection string.
             * @example 'mongodb+srv://...'
             */

            mongoURI: string;
            /**
             * MongoDB database name.
             * @example 'FoundationX'
             */
            mongoDbName: string;
        };
    };

    cluster: StatsBot[];
}
