import { execSync } from 'child_process';
import { AutoGeneratedConfig, Config } from '../types/Config';

export function loadConfig(): Config {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const config = require('../../config.json') as Omit<
        Config,
        keyof AutoGeneratedConfig
    >;

    const autoGeneratedConfig: AutoGeneratedConfig = {
        commit: execSync('git rev-parse HEAD').toString().trim(),
        startedAt: new Date().toISOString(),
        production: process.env.NODE_ENV === 'production',
    };

    return { ...autoGeneratedConfig, ...config };
}
